name: ghp-deploy
on: [push]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build deploy files
        run: |
          quasar build
          
      - name: Deploy Files
        run: |
          cd dist/spa
          git init
          git add -A
          git commit -m 'deploy'
          git push -f git@github.com:tadeaspaule/twitchy-processing-mess.git master:gh-pages
